keywords: ["blip", "lua", "luau", "dev", "development", "debug", "testing", "tools", "logging", "performance"]
type: "Dev"
description: "Dev contains handy functions and attributes for developers."
blocks:
  - text: |
      Dev contains handy functions and attributes for developers.

functions:
    - name: "SetGameThumbnail"
      description: |
          Takes a screenshot and sets it as a thumbnail for the game.
      samples:
          - code: |
              Client.Action3 = function()
                  Dev:SetGameThumbnail()
              end

properties:

    - name: "DisplayBoxes"
      type: "boolean"
      description: |
          Displays [Shape]s' bounding boxes when set to `true`. (`false` by default)

    - name: "DisplayColliders"
      type: "boolean"
      description: |
          Displays collision boxes when set to `true`. (`false` by default)
    
    - name: "DisplayFPS"
      type: "boolean"
      description: |
          Displays a framerate counter when set to `true`. (`false` by default)
