name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:

  # Core Unit Tests
  # -------------------------------------------------- 
  core_unit_tests:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          lfs: 'false'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
          cache-dependency-path: ci/core_unit_tests/go.sum

      - name: Cache Go executable
        id: cache-unit-tests
        uses: actions/cache@v3
        with:
          path: ./ci/core_unit_tests # path to store keys
          # match the os, the main file and its depedencies
          key: ${{ runner.os }}-unit_tests-${{ hashFiles('./ci/format/main.go') }}-${{ hashFiles('./ci/format/go.mod') }}

      - if: steps.cache-unit-tests.outputs.cache-hit != 'true'
        # Build only if necessary
        name: Build Dagger program
        working-directory: ./ci/core_unit_tests
        run: go build -v ./...

      - name: Run Dagger program
        working-directory: ./ci/core_unit_tests
        run: ./unit_tests


  # Format
  # -------------------------------------------------- 
  format:
    name: Core clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          lfs: 'false'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
          cache-dependency-path: ci/format/go.sum

      - name: Cache Go executable
        id: cache-format
        uses: actions/cache@v3
        with:
          path: ./ci/format
          # match the os, the main file and its depedencies
          key: ${{ runner.os }}-format-${{ hashFiles('./ci/format/main.go') }}-${{ hashFiles('./ci/format/go.mod') }}

      - if: steps.cache-format.outputs.cache-hit != 'true'
        name: Build Dagger program        
        working-directory: ./ci/format
        run: go build -v ./...

      - name: Run Dagger program
        working-directory: ./ci/format
        run: ./format

  # other_ci_job:
  #   ...
