services:
    lua-docs:
        build:
            target: website-dev
        ports:
            - 80
        volumes:
            # We mount /content into /www (except for the "audio" directory)
            # - ./content:/www
            - ./content/404.yml:/www/404.yml
            - ./content/cubzh-file-format.md:/www/cubzh-file-format.md
            - ./content/cubzhcheatsheet.yml:/www/cubzhcheatsheet.yml
            - ./content/guides:/www/guides
            - ./content/images:/www/images
            - ./content/index.yml:/www/index.yml
            - ./content/js:/www/js
            - ./content/media:/www/media
            - ./content/modules:/www/modules
            - ./content/reference:/www/reference
            - ./content/style:/www/style
            - ./content/templates:/www/templates
